version: '3.2'

services:
  prometheus:
    build:
      context: Dockerfiles/Prometheus/
    volumes:
      - type: bind
        source: ./Dockerfiles/Prometheus/config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - prometheus

  grafana:
     build:
      context: Dockerfiles/Grafana/
     container_name: grafana
     volumes:
       - type: bind
         source: ./Dockerfiles/Grafana/grafana.ini
         target: /etc/grafana/grafana.ini
     ports:
       - 3000:3000
     networks:
       - prometheus

  nginx:
    build:
      context: ./Dockerfiles/Nginx/
    container_name: nginx
    volumes:
      - ./Dockerfiles/Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 8080:8080
    networks:
      - prometheus

  nginxexporter:
    build:
      context: ./Dockerfiles/NginxExporter/
    container_name: nginxexporter
    ports:
      - 9113:9113
    environment:
      - SCRAPE_URI=http://nginx:8080/stub_status
    depends_on:
      - prometheus
    networks:
      - prometheus

networks:
  prometheus:
    driver: bridge
